// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mismzwqvgukvtordxvwh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1pc216d3F2Z3VrdnRvcmR4dndoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ1MTUzMjksImV4cCI6MjA1MDA5MTMyOX0.y3U24eu6xGlwssmqGOu2FqPVEkH0GZJqvMea_s6j6Qk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);